### ISSUE TITLE
Pi build failing due to missing bootloader package

### ISSUE THREAD

**Issue by alexhaydock** [alexhaydock/pinewall#2]
Seems like for some reason the Pi image build is failing in the `mkimg.arm.sh` script.

```bash
podman run --arch=arm64 --rm -it -v "/var/home/user/git/pinewall/images:/tmp/images:Z" --tmpfs "/tmp/cache" --env PROFILENAME=pinewall_rpi --env TARGETARCH=aarch64 localhost/pinewall-rpi ./imagebuild.sh
OK: 0 MiB in 0 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
v3.15.0-226-g0aa9a217b1 [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
OK: 4820 distinct packages available
>>> mkimage-aarch64: Building pinewall_rpi
>>> mkimage-aarch64: --> rpi_config 00f7d6efeac72ab6a7b7041c034980957ffa8192
>>> mkimage-aarch64: --> rpi_blobs 
gzip: invalid magic
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
make: *** [Makefile:22: rpi] Error 1
```

The bit that seems to be failing is the `build_rpi_blobs()` function:
https://github.com/alpinelinux/aports/blob/f6a6a3540e70accbbeec4c4d6788f56684bb8d48/scripts/mkimg.arm.sh#L1-L5

I think the tar section of that command is failing, with the "gzip: invalid magic" error because it's not being passed anything by the `apk` pipe (because the `raspberrypi-bootloader-common` package only seems to exist in the `edge` branch of Alpine and not in 3.15).

* Edge: https://pkgs.alpinelinux.org/packages?name=raspberrypi-bootloader-common&branch=edge
* 3.15: https://pkgs.alpinelinux.org/packages?name=raspberrypi-bootloader-common&branch=v3.15

Did you need to do anything special to get the Pi image building past this point, @andybroger? I wonder if this is maybe a recent error upstream in Alpine.

The Pi build script definitely worked last time I committed anything to do with Pi support, but I think that might have been before I updated from 3.14 to 3.15, so quite a few months ago.

**Comment by alexhaydock** [comment]
Ah, it looks like that whole structure in `mkimg.arm.sh` arrived in a fairly recent commit on 18th Jan, and that previously the only package that was depended upon was the `raspberrypi-bootloader` package, which does exist in 3.15 and lower:

https://git.alpinelinux.org/aports/commit/?id=9a782440682903971ea57c457135531d26c6d7ab

**Comment by alexhaydock** [comment]
Issue filed upstream since I think I've worked this one out: https://gitlab.alpinelinux.org/alpine/aports/-/issues/13464

**Comment by andybroger** [comment]
Sorry, didn't had any time to work an this project. Got a new opportunity so I think, i will step back for 2 months to focus on that project. Yea, but I think just cloning the `3.15-stable branch` from the aport repo, will do the trick.
Anyway, when we dont build from edge, we should stick to the official version numbers.

Hope this works.

KR Andy

**Comment by alexhaydock** [comment]
> Sorry, didn't had any time to work an this project. Got a new opportunity so I think, i will step back for 2 months to focus on that project. Yea, but I think just cloning the `3.15-stable branch` from the aport repo, will do the trick. Anyway, when we dont build from edge, we should stick to the official version numbers.
> 
> Hope this works.
> 
> KR Andy

I think I managed to work that out just at the same time as you commented - so thanks! :laughing: 

Yeah I noticed that `Dockerfile-image` just checks out the default branch of aports instead of the specific 3.15 branch.

For what it's worth, your fork still has the default behaviour there so you'll probably hit the same issue when you return to the project:
https://github.com/andybroger/pinewall/blob/f142b16ae6ab970b680225180d743b14570c9b4b/Dockerfile_image#L51

My fix that makes use of the ENV vars that already get set in the Dockerfile:
```
RUN git clone --branch "$ALPINEVER-stable" https://gitlab.alpinelinux.org/alpine/aports.git
```
