### ISSUE TITLE
Missing `vlan` package?

### ISSUE THREAD

**Issue by vaskozl** [alexhaydock/pinewall#4]
The default `/etc/network/interfaces` files suggested some vlans, but I can't see the `vlan` package being installed. Without it I don't get any vlans on boot.

I also seem to boot into a weird state, where only some packages are installed if I attempt to add `vlan` to `mkimg.pinewall_rpi.sh`.

Is there some undocumented way to enable vlans via the overlay?

**Comment by vaskozl** [comment]
Looks like there's a conflict with ifupdown-ng: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11885

Supposedly the vlan package isn't actually necessary  anymore as ifupdown-ng looks to support it directly.

**Comment by alexhaydock** [comment]
Do you use the same syntax to name the VLAN and specify the upstream interface with `vlan-raw-device` that I have in the example interfaces file? I can confirm that syntax definitely works in production without the `vlan` package.

I seem to remember that using named interfaces and specifying the VLAN as an argument to the named interface caused me some issues in the past and I had a similar confusion over whether to use the `vlan` package as you seem to be having now.

**Comment by vaskozl** [comment]
Your comment made me spot that I had a mistake in `/etc/network/interface` whereby I had duplicated interface names.

Yup definitely works without the `vlan` package despite what the alpine wiki says!

Thanks

**Comment by alexhaydock** [comment]
Nice! Glad you got it working 😄 

Yeah I've found a few issues with the Alpine Wiki in the past where what it says _was_ true, but is now outdated. It's generally a good resource though.

**Comment by vaskozl** [comment]
I can also now say I have been using a "pinewall" router "in production" since yesterday and the clients haven't even noticed!

Thanks for the project!
